using System.Reflection;

namespace AiCommitMessage
{
    internal class Program
    {
        static void Main(string[] args)
        {
            if (args.Length == 0)
            {
                var versionString = Assembly
                    .GetEntryAssembly()
                    ?.GetCustomAttribute<AssemblyInformationalVersionAttribute>()
                    ?.InformationalVersion.ToString();

                Spectre.Console.AnsiConsole.WriteLine($"AiCommitMessage v{versionString}");
                Spectre.Console.AnsiConsole.WriteLine("-------------");
                Spectre.Console.AnsiConsole.WriteLine("\nUsage:");
                Spectre.Console.AnsiConsole.WriteLine("  AiCommitMessage <message>");
                return;
            }

            ShowBot(string.Join(' ', args));
        }

        static void ShowBot(string message)
        {
            var bot = $"\n        {message}";
            bot +=
                @"
    __________________
                      \
                       \
                          ....
                          ....'
                           ....
                        ..........
                    .............'..'..
                 ................'..'.....
               .......'..........'..'..'....
              ........'..........'..'..'.....
             .'....'..'..........'..'.......'.
             .'..................'...   ......
             .  ......'.........         .....
             .    _            __        ......
            ..    #            ##        ......
           ....       .                 .......
           ......  .......          ............
            ................  ......................
            ........................'................
           ......................'..'......    .......
        .........................'..'.....       .......
     ........    ..'.............'..'....      ..........
   ..'..'...      ...............'.......      ..........
  ...'......     ...... ..........  ......         .......
 ...........   .......              ........        ......
.......        '...'.'.              '.'.'.'         ....
.......       .....'..               ..'.....
   ..       ..........               ..'........
          ............               ..............
         .............               '..............
        ...........'..              .'.'............
       ...............              .'.'.............
      .............'..               ..'..'...........
      ...............                 .'..............
       .........                        ..............
        .....
";
            Spectre.Console.AnsiConsole.WriteLine(bot);
        }
    }
}
