#!/usr/bin/env sh
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(penify|gitauto|dependabot|feature|fix|docs|style|refactor|perf|hotfix|test|chore|create)(\/[a-zA-Z0-9#._-]+)+$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

echo "$local_branch" | grep -qE "$valid_branch_regex" || {
    echo "$message"
    exit 1
}

dotnet tool restore && dotnet csharpier . --check
