title: "AI Commit Message (.NET tool)"
description: "🧠 🧰 This tool generates AI-powered commit messages via Git hooks, automating meaningful message suggestions from OpenAI and others to improve commit quality and efficiency."
baseurl: "dotnet-aicommitmessage"
minimal_mistakes_skin: "plum"
remote_theme: "mmistakes/minimal-mistakes"
repository: "guibranco/dotnet-aicommitmessage"
logo: "docs/images/logo.png"
name: "Guilherme Branco Stracini"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
atom_feed:
  hide: true
author:
  name: "Guilherme Branco Stracinie"
  avatar: "https://guibranco.github.io/photo.png"
  bio: "I am an **amazing** person."
  location: "Dublin, Ireland"
  email: "guilherme@guilhermebranco.com.br"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:guilherme@guilhermebranco.com.br"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://guilhermebranco.com.br"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/guibranco"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/guilherme.stracini"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guibranco"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gui.stracini"
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:guilherme@guilhermebranco.com.br"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://guilhermebranco.com.br"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/guibranco"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/guilherme.stracini"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guibranco"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gui.stracini"
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
