title: "dotnet-aicommitmessage"
description: "🧠 🧰 This tool generates AI-powered commit messages via Git hooks, automating meaningful message suggestions from OpenAI and others to improve commit quality and efficiency."
baseurl: "dotnet-aicommitmessage"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
