name: InferSharp
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  infer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Infer#
        uses: microsoft/infersharpaction@v1.5
        id: runinfersharp

      - name: Upload SARIF output to GitHub Security Center
        uses: github/codeql-action/upload-sarif@v3
        if: success() && hashFiles('infer-out/report.sarif') != ''
        with:
          sarif_file: infer-out/report.sarif
        continue-on-error: true
